In [3]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

from sklearn.metrics import classification_report, confusion_matrix, multilabel_confusion_matrix
from sklearn.metrics import mean_squared_error, accuracy_score, precision_score, recall_score

from sklearn.model_selection import cross_validate

from sklearn.model_selection import KFold

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [4]:
dataset = pd.read_csv("../datasets/statlog+german+credit+data/german.data", sep =" ", header=None, names = ["Status checking", 
                                                                                                        "Duration in month", 
                                                                                                        "Credit history", 
                                                                                                        "Purpose", 
                                                                                                        "Credit amount", 
                                                                                                        "Savings account", 
                                                                                                        "Present employment", 
                                                                                                        "Installment rate %", 
                                                                                                        "Personal status/sex", 
                                                                                                        "Other debtors", 
                                                                                                        "Present residence", 
                                                                                                        "Property", 
                                                                                                        "Age in years", 
                                                                                                        "Other installment plans", 
                                                                                                        "Housing", 
                                                                                                        "# Existing credits", 
                                                                                                        "Job", 
                                                                                                        "# Dependents", 
                                                                                                        "Telephone", 
                                                                                                        "Foreign worker",
                                                                                                        "Class"
                                                                                                        ])
x = dataset.drop('Class', axis=1)
y = dataset['Class']

label_encoder = LabelEncoder()
x["Status checking"] = label_encoder.fit_transform(x["Status checking"])
x["Credit history"] = label_encoder.fit_transform(x["Credit history"])
x["Savings account"] = label_encoder.fit_transform(x["Savings account"])
x["Present employment"] = label_encoder.fit_transform(x["Present employment"])
x["Other debtors"] = label_encoder.fit_transform(x["Other debtors"])
x["Property"] = label_encoder.fit_transform(x["Property"])
x["Other installment plans"] = label_encoder.fit_transform(x["Other installment plans"])
x["Housing"] = label_encoder.fit_transform(x["Housing"])
x["Job"] = label_encoder.fit_transform(x["Job"])
x["Telephone"] = label_encoder.fit_transform(x["Telephone"])
x["Foreign worker"] = label_encoder.fit_transform(x["Foreign worker"])
x["Personal status/sex"] = label_encoder.fit_transform(x["Personal status/sex"])
x['Purpose'] = label_encoder.fit_transform(x['Purpose'])
print(x)
print(y)


# normalize field using min max normalization
scaler = MinMaxScaler(feature_range=(0, 1))
x_scaled = scaler.fit_transform(x)
x = pd.DataFrame(data = x_scaled, columns=x.columns)
# x = pd.DataFrame(data = x, columns=x.columns)

# use one hot encoding
set_of_classes = y.value_counts().index.to_list()
set_of_classes = pd.DataFrame({'Class': set_of_classes})
y = pd.get_dummies(y)

# encode all classes into binary
oec = OneHotEncoder()
y_onehot = oec.fit(np.asarray(y).reshape(-1, 1))
y_onehot = oec.transform(np.asarray(y).reshape(-1, 1)).toarray()

print(x)
print(y)
print(y_onehot)

     Status checking  Duration in month  Credit history  Purpose  \
0                  0                  6               4        4   
1                  1                 48               2        4   
2                  3                 12               4        7   
3                  0                 42               2        3   
4                  0                 24               3        0   
..               ...                ...             ...      ...   
995                3                 12               2        3   
996                0                 30               2        1   
997                3                 12               2        4   
998                0                 45               2        4   
999                1                 45               4        1   

     Credit amount  Savings account  Present employment  Installment rate %  \
0             1169                4                   4                   4   
1             5951       

In [5]:
data_train, data_test, class_train, class_test = train_test_split(x, y, test_size=0.5)


In [4]:

best_params = []
best_score = 0
best_estimator = []

for i in range(100):
    max_iterations = [2000, 3000, 4000, 5000]
    hidden_layer_siz = [(np.random.randint(1, 51), np.random.randint(1, 51)),
                        (np.random.randint(1, 51), np.random.randint(1, 51)),
                        (np.random.randint(1, 51), np.random.randint(1, 51)),
                        (np.random.randint(1, 51), np.random.randint(1, 51)),
                        (np.random.randint(1, 51), np.random.randint(1, 51))]
    learning_rates = 0.02 * np.arange(1, 5)

    param_grid = dict(learning_rate_init=learning_rates,
                      hidden_layer_sizes=hidden_layer_siz,
                      max_iter=max_iterations)
    
    # Create MLP inside the loop with current hyperparameters
    mlp = MLPClassifier(solver='sgd', random_state=42, activation='logistic')

    # For Grid Search
    grid = GridSearchCV(estimator=mlp, param_grid=param_grid)

    # For Random Search
    # grid = RandomizedSearchCV(estimator=mlp, param_distributions=param_grid, n_iter=10)

    grid.fit(x, y)

    if grid.best_score_ > best_score:
        best_params = grid.best_params_
        best_score = grid.best_score_
        best_estimator = grid.best_estimator_

    print("Optimal Hyper-parameters : ", best_params)
    print("Optimal Accuracy : ", best_score)
    
    

Optimal Hyper-parameters :  {'hidden_layer_sizes': (21, 43), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.7619999999999999
Optimal Hyper-parameters :  {'hidden_layer_sizes': (38, 35), 'learning_rate_init': 0.06, 'max_iter': 2000}
Optimal Accuracy :  0.7630000000000001
Optimal Hyper-parameters :  {'hidden_layer_sizes': (49, 11), 'learning_rate_init': 0.02, 'max_iter': 2000}
Optimal Accuracy :  0.7650000000000001
Optimal Hyper-parameters :  {'hidden_layer_sizes': (49, 11), 'learning_rate_init': 0.02, 'max_iter': 2000}
Optimal Accuracy :  0.7650000000000001
Optimal Hyper-parameters :  {'hidden_layer_sizes': (49, 11), 'learning_rate_init': 0.02, 'max_iter': 2000}
Optimal Accuracy :  0.7650000000000001
Optimal Hyper-parameters :  {'hidden_layer_sizes': (49, 11), 'learning_rate_init': 0.02, 'max_iter': 2000}
Optimal Accuracy :  0.7650000000000001
Optimal Hyper-parameters :  {'hidden_layer_sizes': (49, 11), 'learning_rate_init': 0.02, 'max_iter': 2000}
Optimal Accuracy 

c:\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:698: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


Optimal Hyper-parameters :  {'hidden_layer_sizes': (37, 16), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.767
Optimal Hyper-parameters :  {'hidden_layer_sizes': (37, 16), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.767
Optimal Hyper-parameters :  {'hidden_layer_sizes': (37, 16), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.767
Optimal Hyper-parameters :  {'hidden_layer_sizes': (37, 16), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.767
Optimal Hyper-parameters :  {'hidden_layer_sizes': (37, 16), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.767
Optimal Hyper-parameters :  {'hidden_layer_sizes': (37, 16), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.767
Optimal Hyper-parameters :  {'hidden_layer_sizes': (37, 16), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.767
Optimal Hyper-parameters :  {'hidden_layer_sizes': (37, 16), 'learnin

c:\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


Optimal Hyper-parameters :  {'hidden_layer_sizes': (48, 47), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.7670000000000001
Optimal Hyper-parameters :  {'hidden_layer_sizes': (48, 47), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.7670000000000001
Optimal Hyper-parameters :  {'hidden_layer_sizes': (48, 47), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.7670000000000001
Optimal Hyper-parameters :  {'hidden_layer_sizes': (48, 47), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.7670000000000001
Optimal Hyper-parameters :  {'hidden_layer_sizes': (48, 47), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.7670000000000001
Optimal Hyper-parameters :  {'hidden_layer_sizes': (48, 47), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy :  0.7670000000000001
Optimal Hyper-parameters :  {'hidden_layer_sizes': (48, 47), 'learning_rate_init': 0.04, 'max_iter': 2000}
Optimal Accuracy 

In [14]:
mlp = MLPClassifier(activation='logistic', hidden_layer_sizes=(3, 15),
              learning_rate_init=0.3, max_iter=500, random_state=42,
              solver='sgd')
print(mlp)
mlp.fit(x, y)

# Make predictions on the test set
pred = mlp.predict(data_test)
print("Optimal MSE:", mean_squared_error(class_test, pred))

MLPClassifier(activation='logistic', hidden_layer_sizes=(3, 15),
              learning_rate_init=0.3, max_iter=500, random_state=42,
              solver='sgd')
Optimal MSE: 0.193


In [15]:
y = dataset['Class']
y = pd.get_dummies(y)
mlp.fit(data_train, class_train)

pred = mlp.predict(data_test)
print(pred)

[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]

In [16]:
print("Accuracy : ", accuracy_score(class_test, pred))
print("Mean Square Error : ", mean_squared_error(class_test, pred))

print(pred[:5])
print("Confusion Matrix for each label : ")
print(multilabel_confusion_matrix(class_test, pred))

print("Classification Report : ")
print(classification_report(class_test, pred))

Accuracy :  0.766
Mean Square Error :  0.234
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]]
Confusion Matrix for each label : 
[[[ 70  82]
  [ 35 313]]

 [[313  35]
  [ 82  70]]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.79      0.90      0.84       348
           1       0.67      0.46      0.54       152

   micro avg       0.77      0.77      0.77       500
   macro avg       0.73      0.68      0.69       500
weighted avg       0.75      0.77      0.75       500
 samples avg       0.77      0.77      0.77       500



In [17]:
CV = cross_validate(mlp, x, y, cv=10, scoring=['accuracy', 'neg_mean_squared_error'])

print('Accuracy')
print(CV['test_accuracy'])
print('MSE')
print(-1*CV['test_neg_mean_squared_error'])

print('Average Accuracy = ', sum(CV['test_accuracy']) / len(CV['test_accuracy']))
print('Average MSE = ', sum(-1 * CV['test_neg_mean_squared_error']) / len(CV['test_neg_mean_squared_error']))

Accuracy
[0.84 0.67 0.77 0.77 0.72 0.76 0.65 0.73 0.78 0.74]
MSE
[0.16 0.33 0.23 0.23 0.28 0.24 0.35 0.27 0.22 0.26]
Average Accuracy =  0.7430000000000001
Average MSE =  0.257


In [18]:
n_splits=10
kf = KFold(n_splits=n_splits)

acc = 0
mse = 0

In [19]:
i = 0
for train_indices, test_indices in kf.split(x):

    # step 2-3: use k-1/k^th partition for the training/testing model
    start_train, stop_train = train_indices[0], train_indices[-1]+1
    start_test, stop_test = test_indices[0], test_indices[-1]+1
    
    # perform the training similar to Q1
    #this was based on the requirements in Q1
    mlp.fit(x[start_train:stop_train], y[start_train:stop_train])
    pred = mlp.predict(x[start_test:stop_test])
    
    # step 4: record the evaluating scores
    i+=1
    acc += accuracy_score(y[start_test:stop_test], pred)
    mse += mean_squared_error(y[start_test:stop_test], pred)
    
    print("\nAccuracy for batch ", i, " : ", accuracy_score(y[start_test:stop_test], pred))
    print("Mean Square Error for batch ", i, " : ", mean_squared_error(y[start_test:stop_test], pred))

# step 6: find the average and select the batch with highest evaluation scores
print('\nAverage Accuracy = ', acc / n_splits)
print('Average MSE = ', mse / n_splits)


Accuracy for batch  1  :  0.84
Mean Square Error for batch  1  :  0.16

Accuracy for batch  2  :  0.75
Mean Square Error for batch  2  :  0.25

Accuracy for batch  3  :  0.82
Mean Square Error for batch  3  :  0.18

Accuracy for batch  4  :  0.77
Mean Square Error for batch  4  :  0.23

Accuracy for batch  5  :  0.72
Mean Square Error for batch  5  :  0.275

Accuracy for batch  6  :  0.76
Mean Square Error for batch  6  :  0.24

Accuracy for batch  7  :  0.75
Mean Square Error for batch  7  :  0.25

Accuracy for batch  8  :  0.81
Mean Square Error for batch  8  :  0.19

Accuracy for batch  9  :  0.83
Mean Square Error for batch  9  :  0.17

Accuracy for batch  10  :  0.74
Mean Square Error for batch  10  :  0.26

Average Accuracy =  0.7789999999999999
Average MSE =  0.2205
